<?php

include __DIR__ . "/../config/config.php";


use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;

require './assets/lib//PHPMailer/src/Exception.php';
require './assets/lib/PHPMailer/src/PHPMailer.php';
require './assets/lib/PHPMailer/src/SMTP.php';
if (isset($_POST['send'])) {
    $remail = $_POST['remail'];
    $genotp = rand(100000, 999999);
    $mail = new PHPMailer(true);

    try {
        $mail->isSMTP();
        $mail->Host       = 'smtp.hostinger.com';
        $mail->SMTPAuth   = true;
        $mail->Username   = 'Enter Your Email';
        $mail->Password   = 'Enter Your pass';
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
        $mail->Port       = 465;

        //Recipients
        $mail->setFrom('testonly@rexvel.com', 'Rexvel Team');
        $mail->addAddress($remail);
        //Content
        $mail->isHTML(true);
        $mail->Subject = 'OTP Generated by BiMail';
        $mail->Body    = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OTP Verification - BiMail</title>
</head>
<body style="margin: 0; padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; background-color: #f4f4f9; font-family: Helvetica Neue, Arial, sans-serif;">
    <center style="width: 100%; background-color: #f4f4f9;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; margin: 20px auto; border-collapse: collapse;">
            <!-- Header Section -->
            <tr>
                <td style="padding: 30px 0; text-align: center; background-color: #ffffff; border-bottom: 1px solid #e5e7eb;">
                    <img src="https://brainzima.com/assets/img/logo-brainzima-icon.png" alt="BiMail Logo" style="max-width: 150px; height: auto; border: 0; display: block; margin: 0 auto;">
                </td>
            </tr>

            <!-- Content Section -->
            <tr>
                <td style="padding: 40px 30px; background-color: #ffffff; border-radius: 0 0 8px 8px;">
                    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                        <tr>
                            <td style="color: #1f2937; font-size: 24px; font-weight: 600; text-align: center; margin: 0; padding-bottom: 20px;">
                                Verify Your Identity
                            </td>
                        </tr>
                        <tr>
                            <td style="color: #4b5563; font-size: 16px; line-height: 1.5; padding-bottom: 15px;">
                                Hello,
                            </td>
                        </tr>
                        <tr>
                            <td style="color: #4b5563; font-size: 16px; line-height: 1.5; padding-bottom: 20px;">
                                You have requested to verify your account. Please use the One-Time Password (OTP) below to complete the verification process:
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: center; padding: 20px; background-color: #eff6ff; border-radius: 8px; margin: 20px 0;">
                                <span style="font-size: 32px; font-weight: 700; letter-spacing: 6px; color: #4f46e5;">' . $genotp . '</span>
                            </td>
                        </tr>
                        <tr>
                            <td style="color: #4b5563; font-size: 16px; line-height: 1.5; padding-bottom: 20px;">
                                This OTP is valid for <strong>10 minutes</strong>. For your security, please do not share this code with anyone.
                            </td>
                        </tr>
                        <tr>
                            <td style="color: #4b5563; font-size: 16px; line-height: 1.5; padding-bottom: 20px;">
                                If you did not initiate this request, please ignore this email or contact our support team at <a href="mailto:support@bimail.com" style="color: #4f46e5; text-decoration: none; font-weight: 500;">support@bimail.com</a>.
                            </td>
                        </tr>
                        <tr>
                            <td style="color: #4b5563; font-size: 16px; line-height: 1.5;">
                                Best regards,<br>
                                The BiMail Team
                            </td>
                        </tr>
                        <tr>
                            <td style="padding-top: 25px;">
                                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-top: 1px solid #e5e7eb; margin: 25px 0;">
                                    <tr>
                                        <td style="font-size: 12px; color: #6b7280; text-align: center;">
                                            This is an automated message. Please do not reply directly to this email. For assistance, contact <a href="mailto:support@bimail.com" style="color: #4f46e5; text-decoration: none;">support@bimail.com</a>.
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

            <!-- Footer Section -->
            <tr>
                <td style="padding: 20px; text-align: center; background-color: #f4f4f9; font-size: 12px; color: #6b7280;">
                    <p style="margin: 0 0 10px;">© 2025 BiMail. All rights reserved.</p>
                    <p style="margin: 0 0 10px;">Anathalaya Road, Katihar, India</p>
                    <p style="margin: 0;">
                        <a href="#" style="color: #4f46e5; text-decoration: none; margin: 0 10px;">Unsubscribe</a> |
                        <a href="#" style="color: #4f46e5; text-decoration: none; margin: 0 10px;">Privacy Policy</a> |
                        <a href="#" style="color: #4f46e5; text-decoration: none; margin: 0 10px;">Terms of Service</a>
                    </p>
                </td>
            </tr>
        </table>
    </center>
</body>
</html>';
        $mail->AltBody = 'Your otp is : ' . $genotp;

        if ($mail->send()) {
            $sql = "UPDATE admin_tbl SET admin_otp=$genotp WHERE admin_email = '$remail'";
            if (mysqli_query($conn, $sql)) {
                session_start();
                $_SESSION['remail'] = $remail;
                $msg = '<div class="alert alert-success">OTP has been sent!</div>';
                header("Location: verifyOtp.php");
            }
        }
    } catch (Exception $e) {
        echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="A secure password recovery page for your account." />
    <meta name="author" content="" />
    <title>Forgot Password - Your Site Name</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />

    <!-- FontAwesome -->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <style>
        body {
            background: linear-gradient(135deg, #f0f4f8, #d9e4ec);
            font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
        }

        .card {
            border-radius: 14px;
            border: none;
            background: #ffffff;
        }

        .card-header {
            background-color: transparent;
            border-bottom: none;
            text-align: center;
            padding-top: 2rem;
        }

        .card-header h3 {
            font-weight: 600;
            color: #2c3e50;
        }

        .card-body {
            padding: 2rem 2rem;
        }

        .form-floating>label {
            color: #6c757d;
        }

        .btn-primary {
            background: #0d6efd;
            border: none;
            transition: background 0.3s ease-in-out;
        }

        .btn-primary:hover {
            background: #0b5ed7;
        }

        .card-footer {
            background: transparent;
            border-top: none;
        }

        .small a {
            text-decoration: none;
            font-weight: 500;
            color: #0d6efd;
        }

        .small a:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    <div id="layoutAuthentication" class="d-flex align-items-center justify-content-center" style="min-height: 100vh;">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg">
                        <div class="card-header">
                            <h3>Forgot Your Password?</h3>
                            <p class="text-muted small mt-2">Enter your email to receive a password reset link.</p>
                        </div>
                        <div class="card-body">
                            <form action="" method="post">
                                <div class="form-floating mb-4">
                                    <input class="form-control" id="inputEmail" type="email" name="remail" placeholder="name@example.com" aria-label="Enter your email address" required />
                                    <label for="inputEmail">Email address</label>
                                </div>
                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary py-2" name="send">
                                        <i class="fas fa-paper-plane me-2"></i>Send OTP
                                    </button>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center py-3">
                            <div class="small">
                                <a href="login.php"><i class="fas fa-arrow-left me-1"></i>Back to login</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>


</html>
