<?php
include 'config/config.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;


require './admin/assets/lib/PHPMailer/src/Exception.php';
require './admin/assets/lib/PHPMailer/src/PHPMailer.php';
require './admin/assets/lib/PHPMailer/src/SMTP.php';
if (isset($_POST['send'])) {
    $remail = $_POST['remail'];
    $genotp = rand(100000, 999999);
    $mail = new PHPMailer(true);

    try {
        $mail->isSMTP();
        $mail->Host       = 'smtp.hostinger.com';
        $mail->SMTPAuth   = true;
        $mail->Username   = 'Enter Your gmail';
        $mail->Password   = 'Enter Your password';
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
        $mail->Port       = 465;

        //Recipients
        $mail->setFrom('testonly@rexvel.com', 'Rexvel Team');
        $mail->addAddress($remail);
        //Content
        $mail->isHTML(true);
        $mail->Subject = 'OTP Generated by BiMail';
        $mail->Body    = '
            <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OTP Email Template</title>
    <style>
        /* Reset CSS for email compatibility */
        body, table, td, a {
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
        }
        table, td {
            mso-table-lspace: 0pt;
            mso-table-rspace: 0pt;
            border-collapse: collapse;
        }
        img {
            -ms-interpolation-mode: bicubic;
            border: 0;
            height: auto;
            line-height: 100%;
            outline: none;
            text-decoration: none;
        }
        .container {
            width: 100%;
            max-width: 600px;
            margin: 0 auto;
        }
        .main {
            background-color: #f7f7f7;
            border-collapse: collapse;
            width: 100%;
        }
        .content {
            padding: 40px 30px;
            background-color: #ffffff;
            border-radius: 8px;
            font-family: Arial, Helvetica, sans-serif;
            color: #444444;
            line-height: 1.6;
        }
        .logo {
            text-align: center;
            padding: 20px 0;
        }
        .otp-code {
            font-size: 32px;
            font-weight: bold;
            letter-spacing: 5px;
            text-align: center;
            padding: 20px;
            margin: 20px 0;
            background-color: #f2f8ff;
            border-radius: 8px;
            color: #1a73e8;
        }
        .button {
            background-color: #1a73e8;
            border-radius: 4px;
            color: white;
            padding: 12px 30px;
            text-decoration: none;
            display: inline-block;
            margin: 20px 0;
            font-weight: bold;
        }
        .footer {
            padding: 20px;
            text-align: center;
            font-size: 12px;
            color: #999999;
        }
        .text-center {
            text-align: center;
        }
        .divider {
            border-top: 1px solid #eeeeee;
            margin: 25px 0;
        }
        .social-icons {
            margin: 15px 0;
        }
        .social-icons a {
            margin: 0 10px;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <center class="container">
        <table class="main" width="100%" cellpadding="0" cellspacing="0">
            <!-- Logo Section -->
            <tr>
                <td class="logo">
                    <img src="https://via.placehold.com/150x50/1a73e8/ffffff?text=Your+Logo" alt="Company Logo">
                </td>
            </tr>
            
            <!-- Content Section -->
            <tr>
                <td>
                    <table class="content" width="100%" cellpadding="0" cellspacing="0">
                        <tr>
                            <td>
                                <h2 style="color: #1a73e8; margin-top: 0;">Verify Your Identity</h2>
                                <p>Hello Dear,</p>
                                <p>You have requested to access your account. Use the following One-Time Password (OTP) to complete your verification:</p>
                                
                                <div class="otp-code">' . $genotp . '</div>
                                
                                <p>This OTP will expire in <strong>10 minutes</strong>. For security reasons, please do not share this code with anyone.</p>
                                
                                <p>If you did not request this verification, please ignore this email or contact our support team if you have concerns.</p>
                                
                                <p>Thanks,<br>The BiMail Team</p>
                                
                                <div class="divider"></div>
                                
                                <p style="font-size: 12px; color: #999999;">
                                    This is an automated message, please do not reply to this email. 
                                    If you need assistance, contact our support team at support@company.com.
                                </p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <!-- Footer Section -->
            <tr>
                <td class="footer">
                    <p>© 2025 BiMail. All rights reserved.</p>
                    <p>Anathalaya Road, Katihar -India</p>
                    <p>
                        <a href="#" style="color: #999999; text-decoration: none;">Unsubscribe</a> | 
                        <a href="#" style="color: #999999; text-decoration: none;">Privacy Policy</a> | 
                        <a href="#" style="color: #999999; text-decoration: none;">Terms of Service</a>
                    </p>
                </td>
            </tr>
        </table>
    </center>
</body>
</html>
        ';
        $mail->AltBody = 'Your otp is : ' . $genotp;

        if ($mail->send()) {
            $sql = "UPDATE users_tbl SET user_otp=$genotp WHERE user_email = '$remail'";
            if (mysqli_query($conn, $sql)) {
                session_start();
                $_SESSION['remail'] = $remail;
                $msg = '<div class="alert alert-success">OTP has been sent!</div>';
                header("Location: verifyOtp.php");
            }
        }
    } catch (Exception $e) {
        echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Password Reset - SB user</title>
    <link href="admin/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="bg-light d-flex align-items-center justify-content-center vh-100">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-5">
                <div class="card shadow-lg border-0 rounded-4 overflow-hidden">
                    <!-- Header -->
                    <div class="card-header text-center text-white py-4"
                        style="background: linear-gradient(135deg, #0d6efd, #6610f2);">
                        <h3 class="fw-bold mb-1">Password Recovery</h3>
                        <p class="text-white-50 mb-0">We’ll send a password reset link to your email</p>
                    </div>

                    <!-- Body -->
                    <div class="card-body p-4 p-md-5 bg-white">
                        <div class="small mb-4 text-muted text-center">
                            Enter your registered email address to receive a reset link.
                        </div>

                        <form action="" method="post">
                            <div class="form-floating mb-4">
                                <input type="email"
                                    name="remail"
                                    class="form-control rounded-3"
                                    id="inputEmail"
                                    placeholder="name@example.com" required>
                                <label for="inputEmail">
                                    <i class="fa-solid fa-envelope me-2 text-primary"></i>Email address
                                </label>
                            </div>

                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <a href="login.php" class="text-decoration-none text-primary fw-semibold">
                                    <i class="fa-solid fa-arrow-left me-1"></i> Return to Login
                                </a>
                                <button type="submit" name="send"
                                    class="btn btn-primary px-4 py-2 rounded-3 fw-semibold shadow-sm">
                                    <i class="fa-solid fa-paper-plane me-2"></i>Send OTP
                                </button>
                            </div>
                        </form>
                    </div>

                    <!-- Footer -->
                    <div class="card-footer text-center bg-light py-3">
                        <small class="text-muted">Need help?
                            <a href="#" class="text-decoration-none text-primary fw-semibold">Contact Support</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>


</html>
