<?php
include 'config/config.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;
// require "./admin/assets/lib/";
require './admin/assets/lib/PHPMailer/src/Exception.php';
require './admin/assets/lib/PHPMailer/src/PHPMailer.php';
require './admin/assets/lib/PHPMailer/src/SMTP.php';
if (isset($_POST['register'])) {
    $name = $_POST['name'];
    $remail = $_POST['email'];
    $mobile = $_POST['mobile'];
    $password = $_POST['password'];
    $hashPassword = password_hash($password, PASSWORD_DEFAULT);
    $genotp = rand(100000, 999999);
    $mail = new PHPMailer(true);

    try {
        $mail->isSMTP();
        $mail->Host       = 'smtp.hostinger.com';
        $mail->SMTPAuth   = true;
        $mail->Username   = 'Enter Your email';
        $mail->Password   = 'Enter Your Pass';
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
        $mail->Port       = 465;

        //Recipients
        $mail->setFrom('testonly@rexvel.com', 'Rexvel Team');
        $mail->addAddress($remail);
        //Content
        $mail->isHTML(true);
        $mail->Subject = 'OTP Generated by BiMail';
        $mail->Body    = '
            <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OTP Email Template</title>
    <style>
        /* Reset CSS for email compatibility */
        body, table, td, a {
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
        }
        table, td {
            mso-table-lspace: 0pt;
            mso-table-rspace: 0pt;
            border-collapse: collapse;
        }
        img {
            -ms-interpolation-mode: bicubic;
            border: 0;
            height: auto;
            line-height: 100%;
            outline: none;
            text-decoration: none;
        }
        .container {
            width: 100%;
            max-width: 600px;
            margin: 0 auto;
        }
        .main {
            background-color: #f7f7f7;
            border-collapse: collapse;
            width: 100%;
        }
        .content {
            padding: 40px 30px;
            background-color: #ffffff;
            border-radius: 8px;
            font-family: Arial, Helvetica, sans-serif;
            color: #444444;
            line-height: 1.6;
        }
        .logo {
            text-align: center;
            padding: 20px 0;
        }
        .otp-code {
            font-size: 32px;
            font-weight: bold;
            letter-spacing: 5px;
            text-align: center;
            padding: 20px;
            margin: 20px 0;
            background-color: #f2f8ff;
            border-radius: 8px;
            color: #1a73e8;
        }
        .button {
            background-color: #1a73e8;
            border-radius: 4px;
            color: white;
            padding: 12px 30px;
            text-decoration: none;
            display: inline-block;
            margin: 20px 0;
            font-weight: bold;
        }
        .footer {
            padding: 20px;
            text-align: center;
            font-size: 12px;
            color: #999999;
        }
        .text-center {
            text-align: center;
        }
        .divider {
            border-top: 1px solid #eeeeee;
            margin: 25px 0;
        }
        .social-icons {
            margin: 15px 0;
        }
        .social-icons a {
            margin: 0 10px;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <center class="container">
        <table class="main" width="100%" cellpadding="0" cellspacing="0">
            <!-- Logo Section -->
            <tr>
                <td class="logo">
                    <img src="https://via.placehold.com/150x50/1a73e8/ffffff?text=Your+Logo" alt="Company Logo">
                </td>
            </tr>
            
            <!-- Content Section -->
            <tr>
                <td>
                    <table class="content" width="100%" cellpadding="0" cellspacing="0">
                        <tr>
                            <td>
                                <h2 style="color: #1a73e8; margin-top: 0;">Verify Your Identity</h2>
                                <p>Hello Dear,</p>
                                <p>You have requested to access your account. Use the following One-Time Password (OTP) to complete your verification:</p>
                                
                                <div class="otp-code">' . $genotp . '</div>
                                
                                <p>This OTP will expire in <strong>10 minutes</strong>. For security reasons, please do not share this code with anyone.</p>
                                
                                <p>If you did not request this verification, please ignore this email or contact our support team if you have concerns.</p>
                                
                                <p>Thanks,<br>The BiMail Team</p>
                                
                                <div class="divider"></div>
                                
                                <p style="font-size: 12px; color: #999999;">
                                    This is an automated message, please do not reply to this email. 
                                    If you need assistance, contact our support team at support@company.com.
                                </p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <!-- Footer Section -->
            <tr>
                <td class="footer">
                    <p>© 2025 BiMail. All rights reserved.</p>
                    <p>Anathalaya Road, Katihar -India</p>
                    <p>
                        <a href="#" style="color: #999999; text-decoration: none;">Unsubscribe</a> | 
                        <a href="#" style="color: #999999; text-decoration: none;">Privacy Policy</a> | 
                        <a href="#" style="color: #999999; text-decoration: none;">Terms of Service</a>
                    </p>
                </td>
            </tr>
        </table>
    </center>
</body>
</html>
        ';
        $mail->AltBody = 'Your otp is : ' . $genotp;

        if ($mail->send()) {
            $sql = "INSERT INTO users_tbl (user_name, user_mobile, user_email, user_password, user_otp, user_status) VALUES ('$name', '$mobile', '$remail', '$hashPassword',$genotp,'Pending')";
            if (mysqli_query($conn, $sql)) {
                session_start();
                $_SESSION['remail'] = $remail;
                $msg = '<div class="alert alert-success">OTP has been sent!</div>';
                header("Location: verifyAccount.php");
            }
        }
    } catch (Exception $e) {
        echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Create Account - <?= SITENAME ?></title>

    <!-- Bootstrap & Fonts -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <style>
        body {
            background: linear-gradient(135deg, #1a73e8, #6a11cb);
            font-family: 'Poppins', sans-serif;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2rem;
        }

        .card {
            border: none;
            border-radius: 20px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);
            overflow: hidden;
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.2);
        }

        .card-header {
            background: #ffffff;
            border-bottom: none;
            text-align: center;
            padding: 2rem 1rem 1rem;
        }

        .card-header h3 {
            color: #1a73e8;
            font-weight: 600;
            margin-bottom: 0.5rem;
        }

        .card-body {
            padding: 2rem;
            background: #fff;
        }

        .form-floating label {
            color: #666;
        }

        .form-control {
            border-radius: 10px;
            border: 1px solid #ddd;
            transition: all 0.2s;
        }

        .form-control:focus {
            border-color: #1a73e8;
            box-shadow: 0 0 0 0.2rem rgba(26, 115, 232, 0.15);
        }

        .btn-primary {
            background-color: #1a73e8;
            border: none;
            border-radius: 10px;
            padding: 0.75rem 2rem;
            font-weight: 500;
            letter-spacing: 0.5px;
            transition: background 0.3s ease;
        }

        .btn-primary:hover {
            background-color: #1558b0;
        }

        .btn-outline-primary {
            border-radius: 10px;
            padding: 0.5rem 1.5rem;
        }

        .card-footer {
            background: #f9f9f9;
            border-top: none;
            text-align: center;
            font-size: 0.9rem;
            padding: 1.5rem;
        }

        footer {
            text-align: center;
            color: #fff;
            font-size: 0.9rem;
            margin-top: 2rem;
        }

        @media (max-width: 576px) {
            .card {
                border-radius: 15px;
            }

            .card-body {
                padding: 1.5rem;
            }
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h3>Create an Account</h3>
                        <p class="text-muted mb-0">Join us and verify your email securely</p>
                    </div>
                    <div class="card-body">
                        <?php if (!empty($msg)) echo $msg; ?>
                        <form action="" method="post">
                            <div class="form-floating mb-3">
                                <input type="text" name="name" class="form-control" id="inputName" placeholder="Your Name" required>
                                <label for="inputName">Full Name</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="tel" name="mobile" class="form-control" id="inputMobile" placeholder="+91 XXXXXXXXXX" required>
                                <label for="inputMobile">Mobile Number</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="email" name="email" class="form-control" id="inputEmail" placeholder="name@example.com" required>
                                <label for="inputEmail">Email Address</label>
                            </div>
                            <div class="form-floating mb-4">
                                <input type="password" name="password" class="form-control" id="inputPassword" placeholder="Password" required>
                                <label for="inputPassword">Password</label>
                            </div>

                            <div class="d-flex justify-content-between align-items-center mb-4">
                                <a href="forgot-password.php" class="small text-muted">Forgot Password?</a>
                                <button type="submit" name="register" class="btn btn-primary">Create Account</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">
                        <p class="mb-2">Already have an account?</p>
                        <a href="login.php" class="btn btn-sm btn-outline-primary me-2">Login Now</a>
                        <a href="<?= SITEURL ?>" class="btn btn-sm btn-secondary">Go Back</a>
                    </div>
                </div>
            </div>
        </div>

        <footer>
            © <?= date('Y') ?> BiMail. All Rights Reserved.
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>


</html>
